export const DB_PUBLIC_SCHEMA = { schema: 'public' };
export const enum DB_TABLE_NAMES {
  PLAYERS = 'PLAYERS',
  TEAMS = 'TEAMS',
  COMPETITIONS = 'COMPETITIONS',
}

export const PLAYER_ERRORS = {
  COMPETITION_NULL: 'Cannot process if competition not exists.',
};

export const API_FOOTBALL_V4 = {
  URL: 'API_FOOTBALL_URL',
  TOKEN: 'API_FOOTBALL_TOKEN',
  IS_PAYED: 'API_FOOTBALL_IS_PAYED_TOKEN',
  ACCESS_AMOUNT_FREE: 'API_FOOTBALL_ACCESS_AMOUNT_FREE',
  ACCESS_TIME_FREE: 'API_FOOTBALL_ACCESS_TIME_FREE',
};

export enum TRUNCATE_TABLE {
  PLAYERS = 'TRUNCATE TABLE public."PLAYERS" CASCADE',
  TEAMS = 'TRUNCATE TABLE public."PLAYERS" CASCADE',
  COMPETITIONS = 'TRUNCATE TABLE public."COMPETITIONS" CASCADE',
}

export const DB_CONF_FIELDS = {
  HOST: 'DB_HOST',
  PORT: 'DB_PORT',
  DATABASE: 'DB_DATABASE',
  USERNAME: 'DB_USERNAME',
  PASSWORD: 'DB_PASSWORD',
  SYNCHRONIZE: 'DB_SYNCHRONIZE',
  LOGGING: 'DB_LOGGING',
  MIGRATIONS: 'DB_MIGRATIONS',
  MIGRATIONS_TABLE: 'DB_MIGRATIONS_TABLE',
  LOGGER: 'DB_LOGGER',
  AUTOLOAD_ENTITIES: 'DB_AUTOLOAD_ENTITIES',
  URL: 'DB_URL',
};

export const APP = {
  ENV: 'NODE_ENV',
};
